import type {
  Classification,
  KbChunk,
  SuggestedResponse,
  Ticket,
} from "@/types";

interface MockTicket extends Ticket {
  classification: Classification;
  retrievedChunks: { chunk: KbChunk; score: number }[];
  suggestions: SuggestedResponse[];
}

const KB_CHUNKS: Record<string, KbChunk> = {
  "refund-window": {
    id: "k-refund-1",
    documentId: "d-refund",
    documentTitle: "Refund Policy",
    documentUrl: "/kb/billing-refund-policy",
    chunkIndex: 0,
    content:
      "We offer a 14-day money-back guarantee for all paid plans. Refunds must be requested within 14 calendar days of the original charge.",
  },
  "refund-process": {
    id: "k-refund-2",
    documentId: "d-refund",
    documentTitle: "Refund Policy",
    documentUrl: "/kb/billing-refund-policy",
    chunkIndex: 1,
    content:
      "Refunds are processed within 3-5 business days. The money is returned to the original payment method. For credit cards, the refund typically appears on the customer's statement within 5-10 business days, depending on the issuing bank.",
  },
  "refund-not": {
    id: "k-refund-3",
    documentId: "d-refund",
    documentTitle: "Refund Policy",
    documentUrl: "/kb/billing-refund-policy",
    chunkIndex: 2,
    content:
      "Not refundable: charges older than 14 days, add-on features (SMS credits, AI tokens) that have already been consumed, and custom enterprise contracts.",
  },
  "2fa-sms": {
    id: "k-2fa-1",
    documentId: "d-login",
    documentTitle: "Login Troubleshooting Guide",
    documentUrl: "/kb/login-troubleshooting",
    chunkIndex: 0,
    content:
      "For SMS: check that the phone number on file is correct. Carrier delivery can take up to 5 minutes in some regions. Backup codes: each user has 8 single-use backup codes generated at 2FA setup.",
  },
  "2fa-recovery": {
    id: "k-2fa-2",
    documentId: "d-login",
    documentTitle: "Login Troubleshooting Guide",
    documentUrl: "/kb/login-troubleshooting",
    chunkIndex: 1,
    content:
      "If the customer has lost access to both SMS and the authenticator and has no backup codes, an admin must verify identity through a video call before disabling 2FA.",
  },
  "rate-429": {
    id: "k-rate-1",
    documentId: "d-rate",
    documentTitle: "API Rate Limits",
    documentUrl: "/kb/api-rate-limits",
    chunkIndex: 0,
    content:
      "When a customer exceeds their limit, the API returns HTTP 429 with a Retry-After header. The recommended client behavior is exponential backoff starting at the Retry-After value.",
  },
  "rate-spike": {
    id: "k-rate-2",
    documentId: "d-rate",
    documentTitle: "API Rate Limits",
    documentUrl: "/kb/api-rate-limits",
    chunkIndex: 1,
    content:
      "If a customer reports a sudden burst of 429s without changing their integration, check our status page (status.example.com). We occasionally lower limits temporarily during incidents.",
  },
  "export-self": {
    id: "k-export-1",
    documentId: "d-export",
    documentTitle: "Data Export",
    documentUrl: "/kb/data-export",
    chunkIndex: 0,
    content:
      "Self-service export: go to Settings > Data, click Request export, choose format and date range. Customers receive an email when ready - usually within 30 minutes, can take up to 24 hours for large workspaces.",
  },
  "export-large": {
    id: "k-export-2",
    documentId: "d-export",
    documentTitle: "Data Export",
    documentUrl: "/kb/data-export",
    chunkIndex: 1,
    content:
      "If failed, the most common cause is workspace size over 50GB. In that case, recommend they use the API or split the export by date range.",
  },
  "gdpr-route": {
    id: "k-gdpr-1",
    documentId: "d-export",
    documentTitle: "Data Export",
    documentUrl: "/kb/data-export",
    chunkIndex: 2,
    content:
      "If the customer is asking for a GDPR data deletion (not just an export), route the ticket to privacy@example.com. Do not delete data through standard tools - the privacy team has the audited deletion workflow.",
  },
};

const BASE_DATE = new Date("2026-05-13T10:00:00Z").getTime();
const minsAgo = (m: number) => new Date(BASE_DATE - m * 60_000);

export const MOCK_TICKETS: MockTicket[] = [
  {
    id: "t-001",
    customerName: "Sarah Chen",
    customerEmail: "sarah@northstar.io",
    subject: "Refund for plan I never used",
    body: "Hi - I signed up for the Pro plan 5 days ago and life got in the way. I literally have not logged in once since then. Could I get a refund? Order ID is N-49213.",
    createdAt: minsAgo(8),
    status: "open",
    category: "refund",
    priority: "low",
    sentiment: "neutral",
    classification: {
      category: "refund",
      priority: "low",
      sentiment: "neutral",
      reasoning:
        "Refund within policy window, no signs of frustration. Standard case.",
    },
    retrievedChunks: [
      { chunk: KB_CHUNKS["refund-window"], score: 0.91 },
      { chunk: KB_CHUNKS["refund-process"], score: 0.78 },
    ],
    suggestions: [
      {
        id: "s-001-a",
        ticketId: "t-001",
        draft: "Hi Sarah - good news, you're well within the 14-day refund window [doc-1]. I'll process the refund on order N-49213 today. You should see the money back on the original card within 5-10 business days depending on your bank [doc-2]. Anything else I can sort out before you go?",
        confidence: 0.92,
        citations: [KB_CHUNKS["refund-window"], KB_CHUNKS["refund-process"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1840,
        costUsd: 0.0084,
      },
      {
        id: "s-001-b",
        ticketId: "t-001",
        draft: "Sarah, totally understand - life happens. Order N-49213 qualifies under our 14-day guarantee [doc-1], so I'm refunding it now. Money is back to your card in 3-5 business days on our end, 5-10 with most banks [doc-2]. No hard feelings - door's open if you want to give it another shot later.",
        confidence: 0.88,
        citations: [KB_CHUNKS["refund-window"], KB_CHUNKS["refund-process"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1840,
        costUsd: 0.0084,
      },
      {
        id: "s-001-c",
        ticketId: "t-001",
        draft: "Hi Sarah, processing your refund for N-49213 now [doc-1]. Expect 5-10 business days to see it back on the card [doc-2]. Reply here if it doesn't show up by then and I'll dig in.",
        confidence: 0.84,
        citations: [KB_CHUNKS["refund-window"], KB_CHUNKS["refund-process"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1840,
        costUsd: 0.0084,
      },
    ],
  },

  {
    id: "t-002",
    customerName: "Marcus Patel",
    customerEmail: "marcus@buildwise.dev",
    subject: "Production API hit with 429s since 9am",
    body: "We've been on Pro for 6 months, zero changes to our integration. Around 09:00 UTC today we started getting hammered with 429 errors. We are losing requests in production. What's going on?",
    createdAt: minsAgo(14),
    status: "open",
    category: "technical",
    priority: "urgent",
    sentiment: "frustrated",
    classification: {
      category: "technical",
      priority: "urgent",
      sentiment: "frustrated",
      reasoning:
        "Paying customer, production impact, unprovoked spike - likely platform-side issue.",
    },
    retrievedChunks: [
      { chunk: KB_CHUNKS["rate-spike"], score: 0.94 },
      { chunk: KB_CHUNKS["rate-429"], score: 0.82 },
    ],
    suggestions: [
      {
        id: "s-002-a",
        ticketId: "t-002",
        draft: "Marcus - apologies, I can see you're getting hit. A sudden burst of 429s without changes on your side usually means an incident on our end [doc-1]. I'm checking status.example.com and our internal ops channel right now and will be back within 15 min with an update. In the meantime: implement exponential backoff on the Retry-After header [doc-2] to avoid losing the queued requests entirely.",
        confidence: 0.89,
        citations: [KB_CHUNKS["rate-spike"], KB_CHUNKS["rate-429"]],
        model: "claude-sonnet-4-5",
        latencyMs: 2210,
        costUsd: 0.0112,
      },
      {
        id: "s-002-b",
        ticketId: "t-002",
        draft: "Hi Marcus, that's not normal for a stable Pro integration. We sometimes lower limits during incidents to protect the platform [doc-1] - let me check status now. I'll page on-call and reply within 15 minutes. While you wait: clients should already be honoring Retry-After with exponential backoff [doc-2], but worth confirming yours does.",
        confidence: 0.82,
        citations: [KB_CHUNKS["rate-spike"], KB_CHUNKS["rate-429"]],
        model: "claude-sonnet-4-5",
        latencyMs: 2210,
        costUsd: 0.0112,
      },
      {
        id: "s-002-c",
        ticketId: "t-002",
        draft: "Marcus, escalating this to the platform team now - production impact on a paying customer is P1 on our side. I'll have someone on-call respond within 30 min. Quick check: are the 429s coming with a Retry-After header? If yes, exponential backoff [doc-2] will stop you from losing the requests entirely while we dig in.",
        confidence: 0.71,
        citations: [KB_CHUNKS["rate-spike"], KB_CHUNKS["rate-429"]],
        model: "claude-sonnet-4-5",
        latencyMs: 2210,
        costUsd: 0.0112,
      },
    ],
  },

  {
    id: "t-003",
    customerName: "Linda Okafor",
    customerEmail: "linda@everbrew.com",
    subject: "Locked out - 2FA SMS not arriving",
    body: "I'm locked out. SMS codes never come through. Vodafone UK number. Tried 6 times this morning. Changed my phone last month, not sure if that's related. Please help, I have a meeting in 2 hours and I need to access reports.",
    createdAt: minsAgo(22),
    status: "open",
    category: "technical",
    priority: "high",
    sentiment: "frustrated",
    classification: {
      category: "technical",
      priority: "high",
      sentiment: "frustrated",
      reasoning:
        "User blocked from account with time pressure. Recent phone change is a strong signal.",
    },
    retrievedChunks: [
      { chunk: KB_CHUNKS["2fa-sms"], score: 0.93 },
      { chunk: KB_CHUNKS["2fa-recovery"], score: 0.71 },
    ],
    suggestions: [
      {
        id: "s-003-a",
        ticketId: "t-003",
        draft: "Hi Linda - I hear you, let's get you back in before the meeting. Two quick things: (1) since you changed phone last month, the number on file may be the old one - I can verify that on my side, takes 30 seconds. (2) If you have your 8 backup codes from when you set up 2FA, you can use one of those to log in right now [doc-1]. If you don't have them and we confirm the number is outdated, I can disable 2FA after a quick video verification [doc-2] - faster than re-issuing SMS.",
        confidence: 0.86,
        citations: [KB_CHUNKS["2fa-sms"], KB_CHUNKS["2fa-recovery"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1990,
        costUsd: 0.0091,
      },
      {
        id: "s-003-b",
        ticketId: "t-003",
        draft: "Linda - the recent phone change is almost certainly the cause. SMS is going to the old number. Do you still have access to your 8 backup codes from 2FA setup? [doc-1] Those will get you in immediately. If not, reply and I'll start the video verification process [doc-2] - we can complete that in under 20 min.",
        confidence: 0.81,
        citations: [KB_CHUNKS["2fa-sms"], KB_CHUNKS["2fa-recovery"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1990,
        costUsd: 0.0091,
      },
      {
        id: "s-003-c",
        ticketId: "t-003",
        draft: "Hi Linda, given the time pressure I'm flagging this to the on-call admin to start identity verification right now. If you have any of your 8 backup codes [doc-1] from 2FA setup, please reply with one - that's the fastest path. Otherwise we'll need a 5-min video call [doc-2] to disable 2FA on your account.",
        confidence: 0.69,
        citations: [KB_CHUNKS["2fa-sms"], KB_CHUNKS["2fa-recovery"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1990,
        costUsd: 0.0091,
      },
    ],
  },

  {
    id: "t-004",
    customerName: "James O'Reilly",
    customerEmail: "james@oreilly-legal.com",
    subject: "GDPR Article 17 deletion request",
    body: "Per GDPR Article 17, I am requesting the deletion of all personal data associated with my account. Please confirm in writing within the statutory 30-day timeframe.",
    createdAt: minsAgo(45),
    status: "open",
    category: "account",
    priority: "high",
    sentiment: "neutral",
    classification: {
      category: "account",
      priority: "high",
      sentiment: "neutral",
      reasoning:
        "Legal compliance request with statutory deadline. Must be handled by privacy team, not support.",
    },
    retrievedChunks: [{ chunk: KB_CHUNKS["gdpr-route"], score: 0.96 }],
    suggestions: [
      {
        id: "s-004-a",
        ticketId: "t-004",
        draft: "Hi James - thank you for the clear request. GDPR deletions are handled by our privacy team rather than support, so I'm forwarding this to privacy@example.com [doc-1] with the original timestamp preserved. They will reach out directly within 30 days with written confirmation. You'll get a copy of that on this thread as well.",
        confidence: 0.94,
        citations: [KB_CHUNKS["gdpr-route"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1620,
        costUsd: 0.0068,
      },
      {
        id: "s-004-b",
        ticketId: "t-004",
        draft: "James, acknowledging receipt of your Article 17 request. This goes to our privacy team [doc-1] who run the audited deletion workflow - I've routed it now with the timestamp from your original message. They will confirm in writing within the 30-day window. Confirmation will arrive on this thread.",
        confidence: 0.91,
        citations: [KB_CHUNKS["gdpr-route"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1620,
        costUsd: 0.0068,
      },
      {
        id: "s-004-c",
        ticketId: "t-004",
        draft: "Hi James, received and routed to the privacy team [doc-1] - they own GDPR deletions end-to-end. You'll have written confirmation within 30 days from privacy@example.com. The original timestamp on your request is preserved.",
        confidence: 0.88,
        citations: [KB_CHUNKS["gdpr-route"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1620,
        costUsd: 0.0068,
      },
    ],
  },

  {
    id: "t-005",
    customerName: "Yuki Tanaka",
    customerEmail: "yuki@tanaka-studio.jp",
    subject: "Big export not coming through",
    body: "I requested a CSV export 2 days ago and the email never arrived. Workspace has roughly 80GB. What should I do?",
    createdAt: minsAgo(180),
    status: "open",
    category: "technical",
    priority: "medium",
    sentiment: "neutral",
    classification: {
      category: "technical",
      priority: "medium",
      sentiment: "neutral",
      reasoning:
        "Export likely failed silently due to known 50GB limit. Clear path to resolution exists.",
    },
    retrievedChunks: [
      { chunk: KB_CHUNKS["export-large"], score: 0.95 },
      { chunk: KB_CHUNKS["export-self"], score: 0.74 },
    ],
    suggestions: [
      {
        id: "s-005-a",
        ticketId: "t-005",
        draft: "Hi Yuki - at 80GB the export almost certainly failed silently, our self-service path tops out at 50GB [doc-1]. Two options: (1) split the export by date range (e.g. quarterly) and request multiple smaller exports - the self-service tool will handle each one fine [doc-2]. (2) Use our streaming export API which is built exactly for large workspaces. Which one works better for you?",
        confidence: 0.93,
        citations: [KB_CHUNKS["export-large"], KB_CHUNKS["export-self"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1730,
        costUsd: 0.0077,
      },
      {
        id: "s-005-b",
        ticketId: "t-005",
        draft: "Yuki, 80GB is over our self-service export limit so the job failed quietly - that's a UX bug on our side, sorry [doc-1]. The clean path is to split by date range and run multiple smaller exports. Want me to kick off a Q1 / Q2 / Q3 / Q4 batch for you now? [doc-2]",
        confidence: 0.87,
        citations: [KB_CHUNKS["export-large"], KB_CHUNKS["export-self"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1730,
        costUsd: 0.0077,
      },
      {
        id: "s-005-c",
        ticketId: "t-005",
        draft: "Hi Yuki - the 80GB workspace size is the issue, exports over 50GB fail without notification [doc-1]. Fastest fix: request 4 smaller exports split by quarter. If you're comfortable with API integration, our streaming export endpoint is purpose-built for this and can stream the whole 80GB without splitting.",
        confidence: 0.81,
        citations: [KB_CHUNKS["export-large"], KB_CHUNKS["export-self"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1730,
        costUsd: 0.0077,
      },
    ],
  },

  {
    id: "t-006",
    customerName: "Anna Kowalski",
    customerEmail: "anna@kowalski-legal.pl",
    subject: "Charged for plan I cancelled in March",
    body: "I cancelled my Pro subscription on March 8 but I just saw another charge on my card on May 5 for $49. Please refund this immediately. I have the cancellation confirmation email.",
    createdAt: minsAgo(95),
    status: "open",
    category: "billing",
    priority: "high",
    sentiment: "frustrated",
    classification: {
      category: "billing",
      priority: "high",
      sentiment: "frustrated",
      reasoning:
        "Charge after documented cancellation. Customer has evidence. Must investigate and refund quickly.",
    },
    retrievedChunks: [
      { chunk: KB_CHUNKS["refund-window"], score: 0.71 },
      { chunk: KB_CHUNKS["refund-process"], score: 0.66 },
    ],
    suggestions: [
      {
        id: "s-006-a",
        ticketId: "t-006",
        draft: "Anna - I'm sorry, that should not have happened. The May 5 charge after a March 8 cancellation is on us, not within normal policy. I'm refunding the $49 right now - no need to wait for the standard window [doc-1]. You should see it back on the card in 5-10 business days [doc-2]. I'll also escalate this internally so we can figure out why the cancellation didn't propagate to billing - I'll follow up here when I know. Can you forward me the cancellation email so I can attach it to the investigation?",
        confidence: 0.89,
        citations: [KB_CHUNKS["refund-window"], KB_CHUNKS["refund-process"]],
        model: "claude-sonnet-4-5",
        latencyMs: 2080,
        costUsd: 0.0098,
      },
      {
        id: "s-006-b",
        ticketId: "t-006",
        draft: "Hi Anna - that's clearly our mistake. Refunding the $49 charge immediately, regardless of the standard 14-day window [doc-1] since this is a cancelled account. Funds will be back in 5-10 business days [doc-2]. Could you forward me the original cancellation confirmation? I want to look at why your record still showed active so this doesn't happen to anyone else.",
        confidence: 0.84,
        citations: [KB_CHUNKS["refund-window"], KB_CHUNKS["refund-process"]],
        model: "claude-sonnet-4-5",
        latencyMs: 2080,
        costUsd: 0.0098,
      },
      {
        id: "s-006-c",
        ticketId: "t-006",
        draft: "Anna, escalating this to the billing supervisor since it's a charge after cancellation [doc-1] - that's outside what standard support can resolve cleanly. They will refund the $49 directly and follow up on root cause. Expect a reply on this thread within 4 hours. Could you forward me the March 8 cancellation email so it's attached to the case?",
        confidence: 0.72,
        citations: [KB_CHUNKS["refund-window"], KB_CHUNKS["refund-process"]],
        model: "claude-sonnet-4-5",
        latencyMs: 2080,
        costUsd: 0.0098,
      },
    ],
  },

  {
    id: "t-007",
    customerName: "Diego Hernandez",
    customerEmail: "diego@cobalt-design.studio",
    subject: "Old charge - want refund",
    body: "Hi, looking at my statements I see I was charged $588 last year for an annual plan that I never used. Can you refund that please?",
    createdAt: minsAgo(220),
    status: "open",
    category: "refund",
    priority: "low",
    sentiment: "neutral",
    classification: {
      category: "refund",
      priority: "low",
      sentiment: "neutral",
      reasoning:
        "Refund request well outside 14-day window. Need to decline politely and offer alternatives.",
    },
    retrievedChunks: [
      { chunk: KB_CHUNKS["refund-not"], score: 0.93 },
      { chunk: KB_CHUNKS["refund-window"], score: 0.78 },
    ],
    suggestions: [
      {
        id: "s-007-a",
        ticketId: "t-007",
        draft: "Hi Diego - I appreciate the question, but charges older than 14 days are outside our refund window [doc-1] so I'm not able to issue a refund on the annual plan from last year. What I can do: if your current account is still active, I can pause future renewals or downgrade to Free so you're not charged again. Want me to do either?",
        confidence: 0.91,
        citations: [KB_CHUNKS["refund-not"], KB_CHUNKS["refund-window"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1580,
        costUsd: 0.0066,
      },
      {
        id: "s-007-b",
        ticketId: "t-007",
        draft: "Diego, sorry but our refund policy caps at 14 days from the charge [doc-1] [doc-2] - last year's annual is well outside that. I can't refund it. Happy to make sure you're not charged again though - let me know and I'll downgrade the account.",
        confidence: 0.85,
        citations: [KB_CHUNKS["refund-not"], KB_CHUNKS["refund-window"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1580,
        costUsd: 0.0066,
      },
      {
        id: "s-007-c",
        ticketId: "t-007",
        draft: "Hi Diego - unfortunately the 14-day refund window [doc-2] passed long ago on the annual charge from last year [doc-1], so a refund isn't possible here. If you'd like, I can confirm the renewal status of your account so you're not surprised again. Just let me know.",
        confidence: 0.78,
        citations: [KB_CHUNKS["refund-not"], KB_CHUNKS["refund-window"]],
        model: "claude-sonnet-4-5",
        latencyMs: 1580,
        costUsd: 0.0066,
      },
    ],
  },

  {
    id: "t-008",
    customerName: "Aisha Mansour",
    customerEmail: "aisha@meridian.health",
    subject: "Loving the product - one suggestion",
    body: "Hi team, we have been using your platform for 4 months and the experience has been excellent. One thing I miss: bulk-tag operations on records. Right now I can only tag one record at a time which is slow. Is this on the roadmap?",
    createdAt: minsAgo(310),
    status: "open",
    category: "feature_request",
    priority: "low",
    sentiment: "positive",
    classification: {
      category: "feature_request",
      priority: "low",
      sentiment: "positive",
      reasoning:
        "Happy customer, specific actionable feedback. Acknowledge and route to product team.",
    },
    retrievedChunks: [],
    suggestions: [
      {
        id: "s-008-a",
        ticketId: "t-008",
        draft: "Hi Aisha - thanks for the kind words, and that's a fair gripe. Bulk-tag on records has come up a few times. I'll write it up and pass it to the product team with your context, and I'll loop back here if it gets scheduled. In the meantime, the closest workaround is to filter by a shared property and use Saved Views to keep the group together. Not a fix, but it cuts the tedium in half.",
        confidence: 0.62,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1410,
        costUsd: 0.0058,
      },
      {
        id: "s-008-b",
        ticketId: "t-008",
        draft: "Aisha, really appreciate this - we get more useful product feedback from people 4 months in than from anyone else. I don't have visibility into the exact roadmap, but bulk-tag is the kind of ergonomic ask that does land. Logging it with your name attached so product can ping you if they prototype something.",
        confidence: 0.58,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1410,
        costUsd: 0.0058,
      },
      {
        id: "s-008-c",
        ticketId: "t-008",
        draft: "Hi Aisha - glad you're enjoying the platform. I'll forward the bulk-tag suggestion to the product team. I can't confirm if/when it'll ship, but this is exactly the kind of feedback they prioritize. If it gets picked up I'll let you know.",
        confidence: 0.55,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1410,
        costUsd: 0.0058,
      },
    ],
  },

  {
    id: "t-009",
    customerName: "Erik Lindqvist",
    customerEmail: "erik@lindqvist.se",
    subject: "Cannot find my invoices anywhere",
    body: "Where do I download my past invoices? I need them for our accounting. I've looked in Settings but I can't find an Invoices section.",
    createdAt: minsAgo(440),
    status: "open",
    category: "billing",
    priority: "low",
    sentiment: "neutral",
    classification: {
      category: "billing",
      priority: "low",
      sentiment: "neutral",
      reasoning: "Simple product navigation question, low effort to resolve.",
    },
    retrievedChunks: [],
    suggestions: [
      {
        id: "s-009-a",
        ticketId: "t-009",
        draft: "Hi Erik - invoices live under Settings > Billing > Invoice history (not just Settings, which is why it's easy to miss). You can download any of them as PDF. If you need bulk download, let me know the date range and I can put together a zip for you.",
        confidence: 0.7,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1280,
        costUsd: 0.0044,
      },
      {
        id: "s-009-b",
        ticketId: "t-009",
        draft: "Erik, they're tucked one level deeper than expected - Settings > Billing > Invoice history. Each one has a PDF download. Yell if any are missing and I'll pull from our side.",
        confidence: 0.66,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1280,
        costUsd: 0.0044,
      },
      {
        id: "s-009-c",
        ticketId: "t-009",
        draft: "Hi Erik - go to Settings > Billing > Invoice history. All your past invoices are listed there with PDF download links. Let me know if you can't see them and I'll check the account.",
        confidence: 0.6,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1280,
        costUsd: 0.0044,
      },
    ],
  },

  {
    id: "t-010",
    customerName: "Hannah Schwarz",
    customerEmail: "hannah@blackforest.org",
    subject: "Trial extension - can we get another week?",
    body: "Our team has been evaluating but a key stakeholder was on PTO during most of the trial. Any chance we can extend it by 7 days so we can complete the evaluation?",
    createdAt: minsAgo(600),
    status: "open",
    category: "account",
    priority: "medium",
    sentiment: "positive",
    classification: {
      category: "account",
      priority: "medium",
      sentiment: "positive",
      reasoning:
        "Engaged prospect, reasonable request. Standard goodwill extension applies.",
    },
    retrievedChunks: [],
    suggestions: [
      {
        id: "s-010-a",
        ticketId: "t-010",
        draft: "Hi Hannah - no problem, 7-day extensions are standard for cases like this. Just extended your trial until May 20. If you want, I can also set up a quick 20-min walkthrough with our solutions engineer focused on whatever your stakeholder cares about most - usually saves a week of back-and-forth.",
        confidence: 0.66,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1340,
        costUsd: 0.0051,
      },
      {
        id: "s-010-b",
        ticketId: "t-010",
        draft: "Hannah - done, your trial is extended by 7 days (new end date May 20). Hope the stakeholder review goes smoothly. If they want a deeper dive I can put you in touch with someone from the solutions team.",
        confidence: 0.61,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1340,
        costUsd: 0.0051,
      },
      {
        id: "s-010-c",
        ticketId: "t-010",
        draft: "Hi Hannah, granted - trial extended to May 20. Reach out if you need anything specific evaluated during the extension.",
        confidence: 0.57,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1340,
        costUsd: 0.0051,
      },
    ],
  },

  {
    id: "t-011",
    customerName: "Tomas Vargas",
    customerEmail: "tomas@vargas-arq.com.ar",
    subject: "SSO setup - getting metadata error",
    body: "We are setting up SAML SSO with Okta. The login keeps failing with an error about expired metadata. Our IT team says everything looks fine on their end.",
    createdAt: minsAgo(720),
    status: "in_progress",
    category: "technical",
    priority: "medium",
    sentiment: "neutral",
    classification: {
      category: "technical",
      priority: "medium",
      sentiment: "neutral",
      reasoning:
        "Enterprise SSO issue. Specialist queue handles this better than general support.",
    },
    retrievedChunks: [],
    suggestions: [
      {
        id: "s-011-a",
        ticketId: "t-011",
        draft: "Hi Tomas - SAML metadata errors usually mean the metadata cached on either side has expired or is mismatched. To get this resolved fastest I'm routing the ticket to our enterprise SSO queue (enterprise-support@example.com) - they have direct experience with Okta integration quirks. Expect a reply within 2 business hours.",
        confidence: 0.74,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1510,
        costUsd: 0.0061,
      },
      {
        id: "s-011-b",
        ticketId: "t-011",
        draft: "Tomas, routing this to our enterprise SSO specialists - SAML / Okta integration is their daily bread. They'll respond on this thread within 2 hours. While you wait: ask your IT team to re-export the IdP metadata XML and re-upload it on our side - that fixes 70% of metadata errors.",
        confidence: 0.7,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1510,
        costUsd: 0.0061,
      },
      {
        id: "s-011-c",
        ticketId: "t-011",
        draft: "Hi Tomas - escalating to our enterprise SSO team since they have the deeper Okta integration knowledge. You'll hear from them within 2 hours.",
        confidence: 0.63,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1510,
        costUsd: 0.0061,
      },
    ],
  },

  {
    id: "t-012",
    customerName: "Priya Iyer",
    customerEmail: "priya@iyer-clinic.in",
    subject: "Where do I see who else is on my account",
    body: "I want to see all the people who have access to my workspace. Is there a way?",
    createdAt: minsAgo(1100),
    status: "resolved",
    category: "account",
    priority: "low",
    sentiment: "neutral",
    classification: {
      category: "account",
      priority: "low",
      sentiment: "neutral",
      reasoning:
        "Basic navigation question. Already answered and resolved.",
    },
    retrievedChunks: [],
    suggestions: [
      {
        id: "s-012-a",
        ticketId: "t-012",
        draft: "Hi Priya - Settings > Members shows everyone with access to your workspace, including their role and last activity. You can remove anyone you don't recognize from there. Let me know if anything looks off and I can pull the audit log on my side.",
        confidence: 0.74,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1190,
        costUsd: 0.0039,
      },
      {
        id: "s-012-b",
        ticketId: "t-012",
        draft: "Priya, go to Settings > Members. You'll see the full list there.",
        confidence: 0.65,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1190,
        costUsd: 0.0039,
      },
      {
        id: "s-012-c",
        ticketId: "t-012",
        draft: "Hi Priya - the list is at Settings > Members. Includes role and last activity for each person. Let me know if you spot anyone unexpected.",
        confidence: 0.61,
        citations: [],
        model: "claude-sonnet-4-5",
        latencyMs: 1190,
        costUsd: 0.0039,
      },
    ],
  },
];

export function getMockTickets(): MockTicket[] {
  return MOCK_TICKETS;
}

export function getMockTicket(id: string): MockTicket | undefined {
  return MOCK_TICKETS.find((t) => t.id === id);
}
